---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: nginx
spec:
  packageRef:
    refName: nginx.samples.mamachanko.com
    versionSelection:
      constraints: ">= 0.0.0-0"
      prereleases: {}
  serviceAccountName: nginx-install

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-install

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx-install
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx-install
subjects:
  - kind: ServiceAccount
    name: nginx-install
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-install
