apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: nginx.samples.mamachanko.com.0.0.0
spec:
  refName: nginx.samples.mamachanko.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: nginx.samples.mamachanko.com
spec:
  displayName: nginx
  longDescription: nginx.samples.mamachanko.com
  shortDescription: nginx.samples.mamachanko.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: nginx
spec:
  packageRef:
    refName: nginx.samples.mamachanko.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: nginx-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
