#@ load("@ytt:data", "data")

#@ def labels():
app.kubernetes.io/name: nginx
#@ end

---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace
  labels: #@ labels()

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: #@ data.values.namespace
  labels: #@ labels()
spec:
  replicas: #@ data.values.replicas
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
